### ISSUE TITLE
Argument parse fails with trailing whitespace

### ISSUE THREAD

**Issue by Whiteknight** [Whiteknight/StoneFruit#19]
Could not parse all arguments. ' ' fails at Line 1 Column 24
   at StoneFruit.Execution.Arguments.CommandParser.ParseCommand(String command) in C:\projects\StoneFruit\Src\StoneFruit\Execution\Arguments\CommandParser.cs:line 54
   at StoneFruit.Execution.CommandDispatcher.Execute(ArgumentsOrString argsOrString, CancellationToken token) in C:\projects\StoneFruit\Src\StoneFruit\Execution\CommandDispatcher.cs:line 68
   at StoneFruit.Engine.RunOneCommand(ArgumentsOrString command) in C:\projects\StoneFruit\Src\StoneFruit\Engine.cs:line 254

**Comment by Whiteknight** [comment]
This is fixed in v2 now
